### PR TITLE
OKD-40: Use a default RHEL_VERSION when the build argument is not specified

### PR DESCRIPTION
**Pull request by aleskandro**
In OKD, we will always want to keep the "RHEL_VERSION" set by the base CentOS stream image used to build the dtk image.

### CODE REVIEW

**Comment by Prashanth684** [comment]
@bthurber i know you laid out your concerns here: https://github.com/openshift/driver-toolkit/pull/145#issuecomment-2046378848 , but we still feel this will be useful for the community if they want to build and test custom modules. As for the question of support, this will be supported through the community.

**Review by bthurber — APPROVED** [review]
/lgtm

**Pull request merged**
