### PR TITLE
: OKD-216: Patch manifests to require stream-coreos instead of rhel-coreos in the OKD/SCOS case

### PR DESCRIPTION
**Pull request by aleskandro**

### CODE REVIEW

**Comment by LorbusChris** [comment]
Thanks!
/lgtm
/assign @yevgeny-shnaidman

**Comment by sdodson** [comment]
Getting OKD back in order is a critical fix.

**Comment by LorbusChris** [comment]
/retitle: OKD-216: Patch manifests to require stream-coreos instead of rhel-coreos in the OKD/SCOS case

**Pull request merged**
