### PR TITLE
Adding kernel-rpm-macros to the Dockerfile.

### PR DESCRIPTION
**Pull request by ybettan**
This has been requested as an RFE.

[MGMT-12403](https://issues.redhat.com//browse/MGMT-12403)

Signed-off-by: Yoni Bettan <yonibettan@gmail.com>

### CODE REVIEW

**Comment by ybettan** [comment]
FYI @enriquebelarte

**Review by enriquebelarte — APPROVED** [review]

**Comment by ybettan** [comment]
/override ci/prow/e2e-aws-driver-toolkit-presubmit
Nightlies for 4.12 are failing in the last 8 days. Seems like RHCOS build is failing and, therefore, it doesn't get the kernel version it should.

This should affect that PR.

**Pull request merged**
