### PR TITLE
Bug 2000321: changing {product-title} to OpenShift

### PR DESCRIPTION
**Pull request by dcritch**
Noticed some minor typos in the README that were likely left over from another doc.

### CODE REVIEW

**Comment by dagrayvid** [comment]
Thanks for the PR @dcritch.

/approve

**Comment by dcritch** [comment]
@dagrayvid no sweat. Should I make a bz to satisfy that 'tide' check?

**Comment by dcritch** [comment]
Sure thing. https://bugzilla.redhat.com/show_bug.cgi?id=2000321

**Comment by dagrayvid** [comment]
/retitle Bug 2000321: changing {product-title} to OpenShift

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
