### PR TITLE
OCPBUGS-10907: Moving to rhel9 base image.

### PR DESCRIPTION
**Pull request by ybettan**

### CODE REVIEW

**Comment by ybettan** [comment]
/retitle OCPBUGS-10907: Moving to rhel9 base image.

**Comment by yevgeny-shnaidman** [comment]
the only change needed is just moving to rhel9 base image? No need for defining additional repos in order to install packages?

**Comment by ybettan** [comment]
> the only change needed is just moving to rhel9 base image? No need for defining additional repos in order to install packages?

`yum` repos are injected by ART during build time and removed after the build so customer using DTK won't  be able to further install packages that requires entitlements.

**Comment by ybettan** [comment]
/override ci/prow/e2e-aws-driver-toolkit-presubmit
Once the nightlies are stable again this job will mean something.

**Pull request merged**
