### PR TITLE
OKD-40: Add needed options to support building for OKD

### PR DESCRIPTION
**Pull request by ausil**
We are working to have OKD built on CentOS Streaam https://issues.redhat.com/browse/OKD-210 we will be using prow to switch the base image but we need to add the dnf-plugins-core package to the base image and we need to enable the rt repo on CentOS stream 9 in order to make the RT kernel available to be installed.

Specifically this is part of  https://issues.redhat.com/browse/OKD-40  and would need to be backported to 4.15 as well

### CODE REVIEW

**Comment by bthurber** [comment]
@Prashanth684 why is DTK needed for OKD?  DTK is specific to RHOCS/OCP versions and is built solely to provide the needed kernel packages for building OOT kmods.  No applicable to OKD.

**Comment by Prashanth684** [comment]
> @Prashanth684 why is DTK needed for OKD? DTK is specific to RHCOS/OCP versions and is built solely to provide the needed kernel packages for building OOT kmods. No applicable to OKD.

@bthurber why would we not want it to be supported for OKD? is it just a matter of support/documentation or are there technical limitations to it? If someone wants to build a custom module for okd/cs9 why shouldn't that be supported?

**Comment by bthurber** [comment]
> > @Prashanth684 why is DTK needed for OKD? DTK is specific to RHCOS/OCP versions and is built solely to provide the needed kernel packages for building OOT kmods. No applicable to OKD.
> 
> @bthurber why would we not want it to be supported for OKD? is it just a matter of support/documentation or are there technical limitations to it? If someone wants to build a custom module for okd/cs9 why shouldn't that be supported?

Because DTK is built and tied to a specific version of RHCOS kernel, per OCP release including z-streams.  We don't want to expose the kernel packages which require a subscription per the RHEL team.

**Comment by bthurber** [comment]
> > > > @Prashanth684 why is DTK needed for OKD? DTK is specific to RHCOS/OCP versions and is built solely to provide the needed kernel packages for building OOT kmods. No applicable to OKD.
> > > 
> > > 
> > > @bthurber why would we not want it to be supported for OKD? is it just a matter of support/documentation or are there technical limitations to it? If someone wants to build a custom module for okd/cs9 why shouldn't that be supported?
> > 
> > 
> > Because DTK is built and tied to a specific version of RHCOS kernel, per OCP release including z-streams. We don't want to expose the kernel packages which require a subscription per the RHEL team.
> 
> For OKD, we will be building ontop of centos base images, so it should get the centos packages - we should not be exposing any rhel packages in that case.

OK.  The value add for DTK is to be used in conjunction with KMM which is not supported on OKD, strictly OCP.

**Comment by Prashanth684** [comment]
> > > > > @Prashanth684 why is DTK needed for OKD? DTK is specific to RHCOS/OCP versions and is built solely to provide the needed kernel packages for building OOT kmods. No applicable to OKD.
> > > > 
> > > > 
> > > > @bthurber why would we not want it to be supported for OKD? is it just a matter of support/documentation or are there technical limitations to it? If someone wants to build a custom module for okd/cs9 why shouldn't that be supported?
> > > 
> > > 
> > > Because DTK is built and tied to a specific version of RHCOS kernel, per OCP release including z-streams. We don't want to expose the kernel packages which require a subscription per the RHEL team.
> > 
> > 
> > For OKD, we will be building ontop of centos base images, so it should get the centos packages - we should not be exposing any rhel packages in that case.
> 
> OK. The value add for DTK is to be used in conjunction with KMM which is not supported on OKD, strictly OCP.

As I understand, KMM is also [upstream](https://github.com/kubernetes-sigs/kernel-module-management), so I don't see why this should not be applicable to OKD as well and support is not an issue as far as OKD is concerned.

**Comment by bthurber** [comment]
> > > > > > @Prashanth684 why is DTK needed for OKD? DTK is specific to RHCOS/OCP versions and is built solely to provide the needed kernel packages for building OOT kmods. No applicable to OKD.
> > > > > 
> > > > > 
> > > > > @bthurber why would we not want it to be supported for OKD? is it just a matter of support/documentation or are there technical limitations to it? If someone wants to build a custom module for okd/cs9 why shouldn't that be supported?
> > > > 
> > > > 
> > > > Because DTK is built and tied to a specific version of RHCOS kernel, per OCP release including z-streams. We don't want to expose the kernel packages which require a subscription per the RHEL team.
> > > 
> > > 
> > > For OKD, we will be building ontop of centos base images, so it should get the centos packages - we should not be exposing any rhel packages in that case.
> > 
> > 
> > OK. The value add for DTK is to be used in conjunction with KMM which is not supported on OKD, strictly OCP.
> 
> As I understand, KMM is also [upstream](https://github.com/kubernetes-sigs/kernel-module-management), so I don't see why this should not be applicable to OKD as well and support is not an issue as far as OKD is concerned.

KMM is upstream.  There is also no concept of DTK upstream.  The value of KMM paired with DTK downstrem is we can do in-cluster OOT kmod builds whereas that feature isn't supported or available upstream.  This helps support a nice upgrade and lifecycle management experience.  We do not test or plan to support OKD.

**Comment by ausil** [comment]
I believe this PR will fix the failure at https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-driver-toolkit-master-okd-scos-images/1785166056780730368 

This will make sure that changes coming in RHEL down the road that will cause issues are fixed early. I believe there is a lot of value in having the CentOS Stream based version for OKD

**Comment by LorbusChris** [comment]
Let's get this in?
/lgtm

**Comment by Prashanth684** [comment]
> Let's get this in? /lgtm

There was a change made to the base image to include the repo dependency: https://github.com/openshift/images/blob/master/base/Dockerfile.rhel9#L20 which should take care of this issue without the change needed here.

**Comment by LorbusChris** [comment]
Thanks for the pointer, this isn't needed then.
/close

**Pull request closed without merging**
